group 'com.example.flutter_segment'
version '3.12.1'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        namespace "com.example.flutter_segment"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
        coreLibraryDesugaringEnabled true
    }

    buildTypes {
        release {
            consumerProguardFiles 'consumer-rules.pro'
        }
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    dependencies {
        implementation 'com.segment.analytics.android:analytics:4.10.4'
        implementation 'com.segment.analytics.android.integrations:amplitude:3.1.0'
        implementation 'com.appsflyer:segment-android-integration:6.5.2'
        coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}